name: Test and deployment pipeline

on:
  push:
    branches:
      - main
env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
  GITHUB: true
            
jobs:
  test_and_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install for backend
        run: npm ci
      - name: npm install for frontend
        working-directory: client
        run: npm ci
      - name: backend lint
        run: npm run lint
      - name: frontend lint
        working-directory: client
        run: npm run eslint
      - name: build frontend
        working-directory: client
        run: npm run build
      - name: delpoy to heroku
        uses: akhileshns/heroku-deploy@v3.8.9 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstack-bloglist" 
          heroku_email: "abdulgumi77@gmail.com"
          healthcheck: 'https://fullstack-bloglist.herokuapp.com//health'
          checkstring: 'ok'
        env:
          HD_MONGO_URI: ${{ secrets.MONGODB_URI }} 
          HD_SECRET: ${{secrets.SECRET}}
          HD_SKIP_PREFLIGHT_CHECK: true          
