name: Test and deployment pipeline

on:
  push:
    branches:
      - main
env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
  GITHUB: true
            
jobs:
  test_and_deployment_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install for backend
        working-directory: server
        run: npm install
      - name: npm install for frontend
        working-directory: client
        run: npm install
      - name: backend lint
        working-directory: server
        run: npm run lint
      - name: frontend lint
        working-directory: client
        run: npm run eslint
      - name: build frontend
        working-directory: client
        run: npm run build
      - name: test backend
        working-directory: server
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: server 
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
