name: Test and deployment pipeline

on:
  push:
    branches:
      - main
  
jobs:
  test_and_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install for backend
        working-directory: server
        run: npm ci
      - name: npm install for frontend
        working-directory: client
        run: npm ci
      - name: backend lint
        working-directory: server
        run: npm run lint
      - name: frontend lint
        working-directory: client
        run: npm run eslint
      - name: build frontend
        working-directory: client
        run: npm run build
      - name: test backend
        working-directory: server
        run: npm test        
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          GITHUB: true
